### ISSUE TITLE
Getting an integrity constraint exception when running belongsTo example

### ISSUE THREAD

**Issue by j3j5** [beyondcode/tinkerwell-web-docs#1]
When running the example from the docs related to [saving Belongs To relationship](https://github.com/beyondcode/tinkerwell-web-docs/blob/master/laravel/eloquent-relationships.md#belongs-to-relationships) the console returns an integrity constraint error because the column `guest_id` on the `phones` table cannot be null. Weird enough, trying to make it nullable returns a different error (_BadMethodCallException: Call to undefined method Phone::associate()_), see https://web.tinkerwell.app/#/snippets/3af370e2-8ad3-4f4c-9eb1-8412633c7b7a

**Comment by j3j5** [comment]
Congrats for the project btw, this is awesome!!

**Comment by mpociot** [comment]
Hey @j3j5 
sorry for the late reply.
Your code sample is wrong - it should not be `Phone::find(1)->associate()` but `Phone::find(1)->guest()->associate($guest);`

Since you want to associate a model to a specific relation

**Comment by j3j5** [comment]
Hey @mpociot , you are right, but the code sample is from the docs (as linked above) not from me, so it should be changed there then ;) I was just playing around.

No worries for the late reply, busy times for everybody :)
